export default {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  register: "/register",
  dashboard: "/dashboard",
  account: "/dashboard/account",
  topics: "/dashboard/topics",
  chats: "/dashboard/chats",
  chatbot: "/dashboard/chatbot",
  development: "/dashboard/development",
  analytics: "/dashboard/analytics",
  dynamicChatbot: "/chatbot",

  affiliateProgram: "/affiliate-program",
  aboutUs: "/about-us",
  community: "/community",
  careers: "/careers",
  tnc: "/terms-and-conditions",
  privacyPolicy: "/privacy-policy",
};
